### PR TITLE
Add support for symfony 3.x

### PR DESCRIPTION
**Pull request by kissifrot**
This little modification should allow users to add this undle to their symfony 3.x projects.

### CODE REVIEW

**Comment by hpatoio** [comment]
I haven't tested it. But I trust you :smile:

**Comment by kissifrot** [comment]
You don't want to merge it? :)

**Comment by hpatoio** [comment]
LOL I thought I did ! Reopened, merged and re-closed :dancer:

**Comment by kissifrot** [comment]
Thanks! :)
I'll be able to use your bundle again in my sf3 project \o/

**Comment by kissifrot** [comment]
Don't hesitate to tag a release, as it'll become an issue for people migrating to symfony 3: they won't be able to do so without uninstalling the bundle.

**Comment by hpatoio** [comment]
Done !

**Comment by kissifrot** [comment]
Thanks!

**Pull request merged**
